/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.nanai10a.discord.bot.twomeat;

import org.junit.Test;
import static org.junit.Assert.*;

public class GradleLibraryTest {
    @Test public void testSomeLibraryMethod() {
        GradleLibrary classUnderTest = new GradleLibrary();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
