/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.nanai10a.discord.bot.twomeat;

public class GradleLibrary {
    public boolean someLibraryMethod() {
        return true;
    }
}
